export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_ERROR='USER_LOGIN_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT'

export const SIGN_UP_USER= 'SIGN_UP_USER'
export const SIGN_UP_USER_LOADING= 'SIGN_UP_USER_LOADING'


export const ADHERANT_LOADING ='ADHERANT_LOADING'

export const ADD_VACCINATION = 'ADD_VACCINATION';
export const VACCINATION_CONFIRMED = 'VACCINATION_CONFIRMED'

export const RDV_EN_ATTENTE_LOADING = 'RDV_EN_ATTENTE_LOADING'
export const RDV_CONFIRMED_LOADING='RDV_CONFIRMED_LOADING'