export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_ERROR='USER_LOGIN_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT'


export const ADD_VACCINATION = 'ADD_VACCINATION';
export const ADHERANT_LOADING ='ADHERANT_LOADING'